version: "3.5"
services:
  ruby:
    build: ./
    environment:
      - DB=postgres://postgres@postgres:5432/postgres
      - CACHE=redis://redis:6379
    ports:
      - 9000:4567
    volumes:
       - ./:/home/app/myserver
    command: ruby /home/app/myserver/server.rb
    depends_on:
      - 'postgres'
      - 'redis'

  postgres:
    image: postgres:9.6.5

  redis:
    image: redis
 
  

