version: "3.5"
services:
  postgres:
    image: postgres:9.6.5
#    environment:
#      - DB=postgres://postgres@postgres:5432/postgres
    ports:
      - 5432:5432
    
  redis:
    image: redis
#    environment:
#      - CACHE=redis://redis:6379
    ports:
      - 6379:6379
   
  ruby:
#    image: ruby:2.6.0
    build: ./
    environment:
      - DB=postgres://postgres@postgres:5432/postgres
      - CACHE=redis://redis:6379
    ports:
      - 9000:4567
    volumes:
      - "/home/nataly/devops-course-2020/lesson 5/:/home/app/myserver"
    command: ruby /home/app/myserver/server.rb
    depends_on:
      - 'postgres'
      - 'redis'

volumes:
  lesson5:
