version: '3.5'
services:
  postgres:
    image: postgres:9.6.5-alpine
    restart: always
    env_file: .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data/

  ruby:
    build:
      context: ../
      dockerfile: michael.pereverov/Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "9000:4567"

  redis:
    image: redis:6.0.9-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env

volumes:
  postgresql-data:
