version: '3.5'

services:
  
  ruby:   
    build: 
      context: ../
      dockerfile: ./sashka.datsenko/Dockerfile
    ports: 
      - 9000:4567
    environment: 
      DB: postgresql://postgres:testpass@postgres:5432
      CACHE: redis://:testpass@redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:9.6.5
    environment: 
      POSTGRES_PASSWORD: testpass

  redis:
    image: redis
    environment: 
      REDIS_PASSWORD: testpass
    command: redis-server --requirepass testpass
      

